swiftlint_version: 0.47.1

excluded:
  - .vscode
  - .build

opt_in_rules:
  - empty_count
  - empty_string
  - indentation_width

identifier_name:
  min_length: 1
  max_length: 80

type_name:
  min_length: 1
  max_length: 80

indentation: 2

indentation_width:
  indentation_width: 2
