name: Demo
options:
  bundleIdPrefix: dev.mt
packages:
  Main:
    path: ./Main
targets:
  Demo:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [Application]
    dependencies:
      - sdk: SwiftUI.framework
      - package: Main
    settings:
      base:
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1
        OTHER_LDFLAGS: "-Xlinker -interposable -Xlinker -undefined -Xlinker dynamic_lookup"
        INFOPLIST_FILE: "Application/Info.plist"
